config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
    }

    resources :home do
      collection do
        get 'users_details', to: 'home#user_show'
      end

      member do
        get 'edit_user', to: 'home#edit_user'
        patch 'update_user', to: 'home#update_user'
        delete 'destroy_user', to: 'home#destroy_user'
      end
    end

  root 'home#index' 
  
  resources :allotments do
    member do
      get 'deallot'
    end
  end

  resources :brands
  resources :categories

  resources :items do
    member do
      get 'allotments'
      get 'managestock', to: 'items#manage_item_stock'
      patch 'updatestock', to: 'items#update_stock'
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_user_id, only: %i[edit_user update_user destroy_user]

  def index
  end

  def user_show
    @users = User.all
  end

  def edit_user
  end

  def update_user
    if @user.update(user_params)
      redirect_to root_path, flash: {success: "updated successfully"}
    else
      render 'edit_user'  
    end
  end

  def destroy_user
    @user.destroy
    redirect_to root_path, flash: { success: "user destroy" }, status: 303
  end

  private

  def set_user_id
    @user = User.find(params[:id])
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :admin, :password,:password_confirmation)
  end

end

app/views/home/edit_user.html.erb
<%= form_for @user, url: update_user_home_path(id: @user.id) do |f| %>
    <div class="form-outline mb-4">
			<%= f.label :name %><br />
			<%= f.text_field :name, autofocus: true, autocomplete: "Name"%>
    </div>

    <div class="field">
			<%= f.label :email %><br />
			<%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>

    <div class="field">
			<%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
			<%= f.password_field :password, autocomplete: "new-password" %>
			<% if @minimum_password_length %>
					<br />
					<em><%= @minimum_password_length %> characters minimum</em>
			<% end %>
    </div>

    <div class="field">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
    </div>

    <div class="field">
			<%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
			<%= f.password_field :password, autocomplete: "current-password" %>
    </div>

		<div class="field">
			<%= f.label :admin %>
			<%= f.check_box :admin %>
		</div>

    <p>
    	<%= f.submit 'submit', class: "btn btn-primary"%>
    </p>
<%end%>
      

app/views/home/index.html.erb
<div class="home-page page-body h-75 ">
  <%= render 'shared/heading' %>
  <section class="jumbotron bg-white">
    <h1>
      Inventory Management System
    </h1>

    <div class="lead">
      Get your inventory related tasks done here!
    </div>

    <%= image_tag("inventory-management-featured.jpeg", alt: "Inventory Management System") %>

    <% if !user_signed_in? %>
      <div class="button-div">
        <%= link_to "Sign up ", new_user_registration_path, class: "btn btn-lg btn-primary" %>
        <br>
        <%= link_to "Sign in ", new_user_session_path , class: "btn btn-lg btn-primary" %>
      </div>
    <% end %>
  </section>
</div>

app/views/home/user_show.html.erb
<% provide(:title, 'All Users Details') %>

<main class="page-body">
  <%= render 'shared/heading' %>

  <% if @users.blank? %>
    <div>
      NO user have been made as of now.
    </div>

  <% else %>
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>

          <th>Email</th>

          <th>Created At</th>

          <th>Role</th>

          <th>Edit User</th>

        </tr>
      </thead>

      <tbody>
        <% @users.each do |u| %>
          <tr>
            <td>
              <%= u.name %>
            </td>

            <td class="count">
              <%= u.email %>
            </td>

            <td>
              <%= u.created_at %>
            </td>

            <td>
              <%= "Admin" if u.admin? %>
              <%= "User" unless u.admin? %>
            </td>

            <td>
              <%= link_to "Edit", edit_user_home_path(u), class: "btn btn-danger fa-solid fa-trash" %>
              <%= link_to 'destroy', destroy_user_home_path(u),data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger fa-solid fa-trash" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

  <%
=begin%>
 <% if current_user.admin? %>
    <div class="button-div">
      <%= link_to "New Allotment", new_allotment_path, class: "btn btn-lg btn-primary" %>
    </div>
  <% end %> 
<%
=end%>
</main>