config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
    }

    resources :home do
      collection do
        get 'users_details', to: 'home#user_show'
      end

      member do
        get 'edit_user', to: 'home#edit_user'
        patch 'update_user', to: 'home#update_user'
        delete 'destroy_user', to: 'home#destroy_user'
      end
    end

  root 'home#index' 
  
  resources :allotments do
    member do
      get 'deallot'
    end
  end

  resources :brands
  resources :categories

  resources :items do
    member do
      get 'allotments'
      get 'managestock', to: 'items#manage_item_stock'
      patch 'updatestock', to: 'items#update_stock'
    end
  end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
  belongs_to :brand
  has_many :allotments, dependent: :destroy
  has_many :issues, dependent: :destroy

  before_create :set_item_name

  def set_item_name
    self.name = "#{brand.name} #{name}"
  end
  
end

app/controllers/concerns/items/item_module.rb
module Items
  module ItemModule
    extend ActiveSupport::Concern

    def item_create
      item_data = item_params.merge(in_stock: item_params[:total_stock])
      @item = Item.new(item_data)
      if @item.save
        redirect_to @item, flash: {success: "Item created successfully"}
      else
        render 'new'
      end
    end

    def item_update
      previous_quantity = @item&.total_stock
      if((item_params[:total_stock].to_i - previous_quantity + @item.in_stock) < 0)
        redirect_to edit_item_path(@item), flash: { warning: "Currently more items are alloted than entered values." }
      elsif @item.update(item_params)
        redirect_to @item, flash: { success: "Item updated successfully." }
        @item.in_stock += (@item.total_stock - previous_quantity)
      else
        render 'edit'
      end
    end

  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_item_id, only: %i[edit show destroy update]
  include Items::ItemModule

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    item_create
  end

  def edit
  end

  def update
    item_update
  end

  def show
    @brand = Brand.find_by_id(@item&.brand)
    @category = Category.find_by_id(@item&.category)
  end

  def destroy
    @brand.destroy
    redirect_to items_url, flash: { success: "Item deleted." }
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :price, :minimum_required_stock, :quantity, :total_stock, :procurement_time_in_weeks, :brand_id, :category_id)
  end

  def set_item_id
    @item = Item.find(params[:id])
  end


end

app/helpers/items_helper.rb
module ItemsHelper
  include BrandsHelper
  
  def item_display_name(item)
    if !current_user.admin?
      return "<Item deleted>" if item.nil?
      "#{get_brand_name_by_id item.brand_id} #{item.name} (Qty- #{item.in_stock}) -- #{item.category.name}"
    else
      return "<Item deleted>" if item.nil?
      "#{item.name}"
    end
  end

  def get_item_by_id(id)
    return nil if id.nil?
    Item.find(id)
  end
end

app/views/items/_form.html.erb
<%= form_for @item do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="form-group">
    <%= f.label :brand_id, "Brand" %>

    <div class="select-attribute">
      <%= f.collection_select(:brand_id, Brand.all, :id, :name, include_blank: '--Not Allocated--', class: 'form-control') %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :name, "Item Name" %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :category_id, "Category" %>

    <div class="select-attribute">
      <%= f.collection_select(:category_id, Category.all, :id, :name, include_blank: '--Not Allocated--', class: 'form-control') %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :quantity %>
    <%= f.text_field :quantity, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :total_stock %>
    <%= f.number_field :total_stock, min: 0, max: 1000, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :minimum_required_stock %>
    <%= f.number_field :minimum_required_stock, min: 0, max: 1000, class: 'form-control' %>
  </div>

  <%= f.submit submit_text , class: "btn btn-primary form-control" %>
<% end %>

app/views/items/_manage.html.erb
<% if items.blank? %>
  <div>
    NO item has been added as of now.
  </div>

<% else %>
  <table class="table">
    <thead>
      <tr>
        <th>
          Item
        </th>

        <th>
          Category
        </th>

        <th>
          Total stock
        </th>

        <th>
          Currently in stock
        </th>

        <th>
          Minimum Required Stock
        </th>

      </tr>
    </thead>

    <tbody>
      <% items.each do |item| %>
        <tr>
          <td>
            <div>
              <%= item_display_name item %>
            </div>
            <div class="dropdown option-dropdown">
              <a href="#" class="nav-link dropdown-toggle user-dropdown border d-inline btn" data-toggle="dropdown">
                Options
              </a>
              <ul class="dropdown-menu user-menu">
                <li>
                  <%= link_to "Item Details", item_path(item) %>
                </li>

                <li>
                  <%= link_to "Allotment history", allotments_item_path(item) %>
                </li>
              </ul>
            </div>
          </td>

          <td class="count">
            <%= item.category.name %>
          </td>

          <td class="count">
            <%= item.total_stock %>
          </td>

          <td class="count">
            <%= item.in_stock %>
          </td>

          <td class="count">
            <%= item.minimum_required_stock %>
          </td>

        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<% if current_user.admin? %>
  <div class="button-div">
    <%= link_to "Add New Item", new_item_path, class: "btn btn-lg btn-primary"  %>
  </div>
<% end %>

app/views/items/edit.html.erb
<% provide(:title, "Edit Item Details") %>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <main class="page-body">
      <%= render 'shared/heading' %>
      
      <%= render 'form', submit_text: 'Update Item' %>
    </main>
  </div>
</div>

app/views/items/index.html.erb
<% provide(:title, 'All Items') %>

<main class="page-body">
  <%= render 'shared/heading' %>

  <% if user_signed_in? && current_user.admin? %>
    <%= render 'manage', items: @items %>
    
  <% elsif user_signed_in? %>
    <%= render 'shared/assest_cards', asset_type: 'Item' , assets: @items %>
  <% end %>
</main>

app/views/items/new.html.erb
<% provide(:title, "Add New Item") %>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <main class="page-body">
      <%= render 'shared/heading' %>

      <%= render 'form', submit_text: 'Add Item' %>
    </main>
  </div>
</div>

app/views/items/show.html.erb
<% provide(:title, "Item Details: #{item_display_name @item}") %>

<main class="page-body">
  <%= render 'shared/heading' %>

  <% if user_signed_in? && current_user.admin? %>
    <div class="dropdown option-dropdown">
      <a href="#" class="nav-link dropdown-toggle user-dropdown border d-inline btn" data-toggle="dropdown">
        Options
      </a>
      <ul class="dropdown-menu user-menu">
        <li>
          <%= link_to "Edit Item", edit_item_path %>
        </li>

        <li>
          <%= link_to "Delete", @item, method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
        </li>
      </ul>
    </div>
  <% end %>
</main>