config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
    }

    resources :home do
      collection do
        get 'users_details', to: 'home#user_show'
      end

      member do
        get 'edit_user', to: 'home#edit_user'
        patch 'update_user', to: 'home#update_user'
        delete 'destroy_user', to: 'home#destroy_user'
      end
    end

  root 'home#index' 
  
  resources :allotments do
    member do
      get 'deallot'
    end
  end

  resources :brands
  resources :categories

  resources :items do
    member do
      get 'allotments'
      get 'managestock', to: 'items#manage_item_stock'
      patch 'updatestock', to: 'items#update_stock'
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      IMS
    </title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "turbo", type: "module" %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  
  </head>
  <body>
    <header class="navbar navbar-dark navbar-expand-md">
      <div class="container">
        <%= link_to "IMS", root_path, class: 'navbar-brand logo' %>

        <button class="navbar-toggler mobile-view" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <%= image_tag("menu.png", alt: "Navigation menu") %>
        </button>

        <nav class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="nav navbar-nav navbar-right">
            <li class="nav-item">
              <%= link_to "Brands", brands_path %>
            </li>

            <li class="nav-item">
              <%= link_to "Categories", categories_path %>
            </li>

            <li class="nav-item">
              <%= link_to "Items", items_path %>
            </li>

            <li class="nav-item dropdown">
              <a href="#" class="dropdown-toggle user-dropdown" data-toggle="dropdown">
                <% if user_signed_in? %>
                  <%= current_user.email %>
                <% else %>
                  Log in
                <% end %>
              </a>

               <ul class="dropdown-menu user-menu <% if !user_signed_in? %> login <% end %>">
                <% if user_signed_in? %>
                  <li class="nav-item">
                    <% if user_signed_in? %>
                      <%= link_to "All Allotments", allotments_path if current_user.admin? %>
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <% if user_signed_in? %>
                      <%= link_to "Edit Profile", edit_user_registration_path  %>
                    <% end %>
                  </li>

                  <li class="nav-item">
                    <% if user_signed_in? %>
                      <%= link_to "All Users", users_details_home_index_path if current_user.admin? %>
                    <% end %>
                  </li>

                  <li>
                    <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }%>
                  </li>
                <% end %>
              </ul>
            </li>
          </ul>
        </nav>
      </div>
    </header>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>